# Generated by Django 6.0.4 on 2026-05-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(default="male", max_length=50),
        ),
    ]
