# Generated by Django 6.0.4 on 2026-05-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
