# Generated by Django 6.0.4 on 2026-05-14 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_profile_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
                ("experience", models.IntegerField()),
                ("discription", models.CharField(max_length=100)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("skills", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=100)),
                ("startsalary", models.IntegerField()),
                ("sallaryrange", models.IntegerField()),
                ("deadline", models.DateField()),
                ("vacancies", models.IntegerField()),
                ("location", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="myapp.employee",
                    ),
                ),
            ],
        ),
    ]
