# Generated by Django 6.0.4 on 2026-05-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_jobs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="salary",
        ),
    ]
