# Generated by Django 6.0.4 on 2026-05-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_jobs_salary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobs",
            old_name="sallaryrange",
            new_name="maxsalary",
        ),
        migrations.RenameField(
            model_name="jobs",
            old_name="startsalary",
            new_name="minsalary",
        ),
    ]
