# Generated by Django 6.0.4 on 2026-05-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_rename_sallaryrange_jobs_maxsalary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="resume",
        ),
    ]
