# Generated by Django 6.0.4 on 2026-05-21 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_remove_jobs_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eligibilty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(blank=True, null=True, upload_to="media/")),
                ("skills", models.CharField(max_length=50)),
                ("experience", models.IntegerField()),
                ("current_salary", models.IntegerField()),
                ("apply_date", models.DurationField()),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "choice1"), ("B", "choice2")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to="myapp.employee",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="myapp.user",
                    ),
                ),
            ],
        ),
    ]
