# Generated by Django 6.0.4 on 2026-05-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_eligibilty"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilty",
            name="education",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilty",
            name="skills",
            field=models.CharField(max_length=100),
        ),
    ]
