# Generated by Django 6.0.4 on 2026-05-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_eligibilty_education_alter_eligibilty_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Eligibilty",
            new_name="Application",
        ),
    ]
