# Generated by Django 6.0.4 on 2026-05-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_rename_eligibilty_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="myapp.jobs",
            ),
        ),
    ]
