# Generated by Django 6.0.4 on 2026-05-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_application_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="apply_date",
            field=models.DateTimeField(),
        ),
    ]
