# Generated by Django 6.0.4 on 2026-05-28 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.CharField(max_length=100)),
                ("opt_a", models.CharField(max_length=50)),
                ("opt_b", models.CharField(max_length=50)),
                ("opt_c", models.CharField(max_length=50)),
                ("opt_d", models.CharField(max_length=50)),
                ("answer", models.CharField(max_length=50)),
                ("marks", models.IntegerField()),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to="myapp.employee",
                    ),
                ),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile",
                        to="myapp.courses",
                    ),
                ),
            ],
        ),
    ]
