# Generated by Django 6.0.4 on 2026-05-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_questions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Courses",
            new_name="Category",
        ),
    ]
