# Generated by Django 6.0.4 on 2026-05-28 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_rename_courses_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to="myapp.employee",
            ),
        ),
    ]
