# Generated by Django 5.2.9 on 2026-06-04 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_questions_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='education',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='application',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='education',
        ),
        migrations.AddField(
            model_name='application',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='emp_pp/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('HR Executive', 'HR Executive'), ('Employee', 'Employee'), ('Manager', 'Manager')], default='Employee', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Under Review', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('Software Developer', 'Software Developer'), ('Senior Developer', 'Senior Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Data Analyst', 'Data Analyst'), ('QA Tester', 'QA Tester'), ('Accountant', 'Accountant'), ('Sales Executive', 'Sales Executive'), ('Marketing Executive', 'Marketing Executive'), ('Technician', 'Technician'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('0-1 years', '0-1 years'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3+ years', 'More than 3 years')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=100)),
                ('opt_a', models.CharField(max_length=50)),
                ('opt_b', models.CharField(max_length=50)),
                ('opt_c', models.CharField(max_length=50)),
                ('opt_d', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='myapp.employee')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to='myapp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
