# Generated by Django 5.2.9 on 2026-06-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_category_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='experience',
        ),
    ]
