# Generated by Django 5.2.9 on 2026-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_application_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
