# Generated by Django 5.2.9 on 2026-06-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_application_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
    ]
