# Generated by Django 5.2.9 on 2026-06-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.job'),
        ),
    ]
