# Generated by Django 5.2.9 on 2026-06-09 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_test_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job'),
        ),
    ]
