# Generated by Django 5.2.9 on 2026-06-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_application_status_interview_selection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interview_type',
        ),
    ]
