# Generated by Django 5.2.9 on 2026-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_interview_interview_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('HR', 'HR')], default='Technical', max_length=20),
        ),
    ]
