from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('index-2/', views.index_2, name='index_2'),
    path('about/', views.about, name='about'),
    path('add-resume/', views.add_resume, name='add_resume'),
    path('base/', views.base, name='base'),
    path('blog/', views.blog, name='blog'),
    path('blog-full-width/', views.blog_full_width, name='blog_full_width'),
    path('blog-left-sidebar/', views.blog_left_sidebar, name='blog_left_sidebar'),
    path('bookmarked/', views.bookmarked, name='bookmarked'),
    path('browse-categories/', views.browse_categories, name='browse_categories'),
    path('browse-jobs/', views.browse_jobs, name='browse_jobs'),
    path('browse-resumes/', views.browse_resumes, name='browse_resumes'),
    path('change-password/', views.change_password, name='change_password'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('job-alerts/', views.job_alerts, name='job_alerts'),
    path('job-details/', views.job_details, name='job_details'),
    path('job-page/', views.job_page, name='job_page'),
    path('manage-applications/', views.manage_applications, name='manage_applications'),
    path('manage-jobs/', views.manage_jobs, name='manage_jobs'),
    path('manage-resumes/', views.manage_resumes, name='manage_resumes'),
    path('notifications/', views.notifications, name='notifications'),
    path('post-job/', views.post_job, name='post_job'),
    path('pricing/', views.pricing, name='pricing'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('resume/', views.resume, name='resume'),
    path('single-post/', views.single_post, name='single_post'),
    # path('create/',  views.create_jobs, name= 'createjobs'),
    path('register/',views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
 
    path('profile/', views.user_profile, name='user_profile'),
    path('profile2/',views.employee_profile,name='employee_profile'),
    path('add/', views.add_employee , name ='add_employee'),
    path('jobs/', views.vacancy, name='vacancy'),
    path('eligibility/<int:id>',views.eligibility, name='eligibility'),
    path('side/', views.side , name='side'),
    path('test/',views.test, name='test')
]
